Repository threeal/bro, pull requests merged in 2023-01, with the labels that each got.

#17 Audit Workflows
  .github/workflows/build.yml
Labels: github_actions

#16 feat: add threeal bot service
  service/svc.sh
  service/threeal-bot.service
Labels: enhancement

#34 Include `.git` Directory for Coveralls Upload
  .github/workflows/build.yml
Labels: bug

#35 Fail Coverage Test If Below Threshold
  .github/workflows/build.yml
  pkg/cli/main_test.go
  pkg/internal/testing.go
  pkg/service/main_test.go
  pkg/tcp/main_test.go
  pkg/utils/main_test.go
Labels: bug

#31 Feat/add config
  README.md
  cmd/bro-backend/config.go
  cmd/bro-backend/main.go
  cmd/bro/config.go
  cmd/bro/main.go
  go.mod
  go.sum
  pkg/utils/config.go
  pkg/utils/config_test.go
  service/bro.service
Labels: enhancement, dependencies, go
